src/Entity/FicheProspection.php
<?php

namespace App\Entity;

use App\Repository\FicheProspectionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FicheProspectionRepository::class)
 */
class FicheProspection
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $nom_entreprise;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $raison_sociale_entreprise;

    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $code_ape;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $rue_entreprise;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $ville_entreprise;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $code_postal_entreprise;

    /**
     * @ORM\Column(type="string", length=40, nullable=true)
     */
    private $telephone_fixe_entreprise;

    /**
     * @ORM\Column(type="string", length=40, nullable=true)
     */
    private $telephone_portable_entreprise;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email_entreprise;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_derniere_modification;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="fiches_prospection")
     */
    private $responsable_fiche_prospection;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    private $siret_siren;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_creation;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $statut;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEntreprise(): ?string
    {
        return $this->nom_entreprise;
    }

    public function setNomEntreprise(string $nom_entreprise): self
    {
        $this->nom_entreprise = $nom_entreprise;

        return $this;
    }

    public function getRaisonSocialeEntreprise(): ?string
    {
        return $this->raison_sociale_entreprise;
    }

    public function setRaisonSocialeEntreprise(string $raison_sociale_entreprise): self
    {
        $this->raison_sociale_entreprise = $raison_sociale_entreprise;

        return $this;
    }

    public function getCodeApe(): ?string
    {
        return $this->code_ape;
    }

    public function setCodeApe(?string $code_ape): self
    {
        $this->code_ape = $code_ape;

        return $this;
    }

    public function getRueEntreprise(): ?string
    {
        return $this->rue_entreprise;
    }

    public function setRueEntreprise(?string $rue_entreprise): self
    {
        $this->rue_entreprise = $rue_entreprise;

        return $this;
    }

    public function getVilleEntreprise(): ?string
    {
        return $this->ville_entreprise;
    }

    public function setVilleEntreprise(?string $ville_entreprise): self
    {
        $this->ville_entreprise = $ville_entreprise;

        return $this;
    }

    public function getCodePostalEntreprise(): ?string
    {
        return $this->code_postal_entreprise;
    }

    public function setCodePostalEntreprise(?string $code_postal_entreprise): self
    {
        $this->code_postal_entreprise = $code_postal_entreprise;

        return $this;
    }

    public function getTelephoneFixeEntreprise(): ?string
    {
        return $this->telephone_fixe_entreprise;
    }

    public function setTelephoneFixeEntreprise(?string $telephone_fixe_entreprise): self
    {
        $this->telephone_fixe_entreprise = $telephone_fixe_entreprise;

        return $this;
    }

    public function getTelephonePortableEntreprise(): ?string
    {
        return $this->telephone_portable_entreprise;
    }

    public function setTelephonePortableEntreprise(?string $telephone_portable_entreprise): self
    {
        $this->telephone_portable_entreprise = $telephone_portable_entreprise;

        return $this;
    }

    public function getEmailEntreprise(): ?string
    {
        return $this->email_entreprise;
    }

    public function setEmailEntreprise(?string $email_entreprise): self
    {
        $this->email_entreprise = $email_entreprise;

        return $this;
    }

    public function getDateDerniereModification(): ?\DateTimeInterface
    {
        return $this->date_derniere_modification;
    }

    public function setDateDerniereModification(?\DateTimeInterface $date_derniere_modification): self
    {
        $this->date_derniere_modification = $date_derniere_modification;

        return $this;
    }

    public function getResponsableFicheProspection(): ?User
    {
        return $this->responsable_fiche_prospection;
    }

    public function setResponsableFicheProspection(?User $responsable_fiche_prospection): self
    {
        $this->responsable_fiche_prospection = $responsable_fiche_prospection;

        return $this;
    }

    public function getSiretSiren(): ?string
    {
        return $this->siret_siren;
    }

    public function setSiretSiren(?string $siret_siren): self
    {
        $this->siret_siren = $siret_siren;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(?\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(?string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }
}

src/Controller/FicheProspectionController.php
<?php


namespace App\Controller;


use App\Entity\FicheProspection;
use App\Form\FicheProspectionType;
use App\Form\FicheProspectionUserType;
use App\Repository\FicheProspectionRepository;
use App\Repository\UserRepository;
use DateTime;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\Mailer\Exception\TransportExceptionInterface;

class FicheProspectionController extends AbstractController
{
    /**
     * @Route("admin/fiche-prospection/ajouter", name="app_add_admin_fiche_prospection")
     * @param Request $request
     * @param ValidatorInterface $validator
     * @param MailerInterface $mailer
     * @param UserRepository $userRepository
     * @return RedirectResponse|Response
     * @throws TransportExceptionInterface
     */
    public function addFicheProspectionAdmin(Request $request, ValidatorInterface $validator, MailerInterface $mailer, UserRepository $userRepository)
    {
        $fiche_prospection = new FicheProspection();
        $form = $this->createForm(FicheProspectionType::class,$fiche_prospection);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            $fiche_prospection = $form->getData();
            $fiche_prospection->setDateCreation(new DateTime());
            $fiche_prospection->setStatut('Validé');
            $em = $this->getDoctrine()->getManager();
            $em->persist($fiche_prospection);
            $em->flush();

            $errors = $validator->validate($fiche_prospection);
            if(count($errors)>0)
            {
                $this->addFlash('error','Une erreur est survenue !');
                return $this->redirectToRoute('app_add_admin_fiche_prospection');
            }
            else
            {
                $this->addFlash('success','Fiche de prospection : '.$form->get('nomEntreprise')->getData().' ajoutée avec succès !');
                $responsable = $userRepository->find($fiche_prospection->getResponsableFicheProspection());
                $email = (new TemplatedEmail())
                    ->from('avis@monprocertifie.fr')
                    ->to($responsable->getEmail())
                    ->subject('Attribution d\'une nouvelle fiche de prospection - MonProCertifié')
                    ->htmlTemplate('emails/admin_add_prospection.html.twig')
                    ->context([
                        "nomResponsable"=>$responsable->getNom(),
                        "prenomResponsable"=>$responsable->getPrenom(),
                        "nomFicheEntreprise"=>$fiche_prospection->getNomEntreprise(),
                        "dateCreation"=>$fiche_prospection->getDateCreation()
                    ])
                ;
                $mailer->send($email);
                return $this->redirectToRoute('app_add_admin_fiche_prospection');
            }
        }
        return $this->render('admin/prospection/add_fiche_prospection.html.twig',['formulaire'=>$form->createView()]);
    }

    /**
     * @Route("/fiche-prospection/ajouter", name="app_add_user_fiche_prospection")
     * @param Request $request
     * @param ValidatorInterface $validator
     * @param MailerInterface $mailer
     * @param UserRepository $userRepository
     * @return RedirectResponse|Response
     * @throws TransportExceptionInterface
     */
    public function addFicheProspectionUser(Request $request, ValidatorInterface $validator, MailerInterface $mailer, UserRepository $userRepository)
    {
        $fiche_prospection_user = new FicheProspection();
        $form = $this->createForm(FicheProspectionUserType::class,$fiche_prospection_user);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            $fiche_prospection_user = $form->getData();
            $fiche_prospection_user->setDateCreation(new DateTime());
            $responsable_courant = $userRepository->findOneBy(['email'=>$this->getUser()->getUsername()]);
            $fiche_prospection_user->setResponsableFicheProspection($responsable_courant);
            $fiche_prospection_user->setStatut("En attente");
            $em = $this->getDoctrine()->getManager();
            $em->persist($fiche_prospection_user);
            $em->flush();

            $errors = $validator->validate($fiche_prospection_user);
            if(count($errors)>0)
            {
                $this->addFlash('error','Une erreur est survenue !');
                return $this->redirectToRoute('app_add_user_fiche_prospection');
            }
            else
            {
                $this->addFlash('success','Fiche de prospection : '.$form->get('nomEntreprise')->getData().' ajoutée avec succès !');
                $email = (new TemplatedEmail())
                    ->from('avis@monprocertifie.fr')
                    ->to('aleksandra@monprocertifie.fr','anthony@monprocertifie.fr')
                    ->subject('Création d\'une nouvelle fiche de prospection - MonProCertifié')
                    ->htmlTemplate('emails/admin_add_prospection_user.html.twig')
                    ->context([
                        "nomResponsable"=>$responsable_courant->getNom(),
                        "prenomResponsable"=>$responsable_courant->getPrenom(),
                        "nomFicheEntreprise"=>$fiche_prospection_user->getNomEntreprise(),
                        "dateCreation"=>$fiche_prospection_user->getDateCreation(),
                        "pathFiche"=>$this->generateUrl('app_admin_modifier_fiche_prospection',['id'=>$fiche_prospection_user->getId()],UrlGeneratorInterface::ABSOLUTE_URL),
                        "pathFicheValidation"=>$this->generateUrl('app_admin_valider_fiche_prospection_automatique',['id'=>$fiche_prospection_user->getId()],UrlGeneratorInterface::ABSOLUTE_URL)
                    ])
                ;
                $mailer->send($email);
                return $this->redirectToRoute('app_add_user_fiche_prospection');
            }
        }
        return $this->render('ficheprospection/add_fiche_prospection_user.html.twig',['formulaire'=>$form->createView()]);
    }

    /**
     * @Route("/admin/fiches-prospection/", name="app_admin_liste_fiche_prospection")
     * @param FicheProspectionRepository $ficheProspectionRepository
     * @return Response
     */
    public function listeFichesProspectionAdmin(FicheProspectionRepository $ficheProspectionRepository)
    {
        $fiches_prospections = $ficheProspectionRepository->findAll();
        if(!$fiches_prospections)
        {
            $this->addFlash('error','Aucune fiche de prospection pour le moment');
            return $this->render('admin/index.html.twig');
        }
        else
        {
            return $this->render('admin/prospection/liste_fiches_prospection.html.twig',['fiches'=>$fiches_prospections]);
        }
    }

    /**
     * @Route("/fiches-prospection/", name="app_user_liste_fiche_prospection")
     * @param FicheProspectionRepository $ficheProspectionRepository
     * @param UserRepository $userRepository
     * @return Response
     */
    public function listeFichesProspectionUser(FicheProspectionRepository $ficheProspectionRepository, UserRepository $userRepository)
    {
        $current_user = $this->getUser()->getUsername();
        $responsable = $userRepository->findOneBy(['email'=>$current_user]);
        $fiches_prospections = $ficheProspectionRepository->findBy(['responsable_fiche_prospection'=>$responsable->getId(),'statut'=>'Validé']);
        if(!$fiches_prospections)
        {
            $this->addFlash('error','Vous n\'avez aucune fiche de prospection pour le moment');
            return $this->render('admin/index.html.twig');
        }
        else
        {
            return $this->render('ficheprospection/liste_fiches_prospection_user.html.twig',['fiches'=>$fiches_prospections]);
        }
    }

    /**
     * @Route("/admin/modification-responsable", name="app_admin_modification_responsable")
     * @param Request $request
     * @param FicheProspectionRepository $ficheProspectionRepository
     * @param UserRepository $userRepository
     * @param MailerInterface $mailer
     * @return Response
     * @throws TransportExceptionInterface
     */
    public function modificationResponsableAjax(Request $request, FicheProspectionRepository $ficheProspectionRepository, UserRepository $userRepository, MailerInterface $mailer)
    {
        if($request->isXmlHttpRequest())
        {
            $id_fiche = $request->request->get('id_fiche');
            $id_responsable = $request->request->get('id_responsable');

            $fiche_concernee = $ficheProspectionRepository->find($id_fiche);
            $responsable = $userRepository->find($id_responsable);

            if($id_responsable === 'NULL')
            {
                $fiche_concernee->setResponsableFicheProspection(null);
            }
            else
            {
                $fiche_concernee->setResponsableFicheProspection($responsable);
                $email = (new TemplatedEmail())
                    ->from('avis@monprocertifie.fr')
                    ->to($responsable->getEmail())
                    ->subject('Attribution d\'une nouvelle fiche de prospection - MonProCertifié')
                    ->htmlTemplate('emails/admin_add_prospection.html.twig')
                    ->context([
                        "nomResponsable"=>$responsable->getNom(),

templates/ficheprospection/add_fiche_prospection_user.html.twig
{% extends 'base.html.twig' %}

{% block title %} Ajouter une fiche de prospection - {{ parent() }} {% endblock %}

{% block body %}
    <div class="container mb-4">
        <div class="row">
            <h1 class="center-align">Nouvelle fiche de prospection</h1>
        </div>
        <div class="row mt-4">
            {% if formulaire is defined %}
                {{ form_start(formulaire, { 'attr': { 'class': 'validate' } }) }}
                <div class="row">
                    <div class="input-field col s6">
                        <i class="material-icons prefix">business</i>
                        {{ form_widget(formulaire.nomEntreprise, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.nomEntreprise) }}
                        {{ form_help(formulaire.nomEntreprise) }}
                        {{ form_errors(formulaire.nomEntreprise) }}
                    </div>
                    <div class="input-field col s6">
                        <i class="material-icons prefix">poll</i>
                        {{ form_widget(formulaire.raisonSocialeEntreprise, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.raisonSocialeEntreprise) }}
                        {{ form_help(formulaire.raisonSocialeEntreprise) }}
                        {{ form_errors(formulaire.raisonSocialeEntreprise) }}
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        <i class="material-icons prefix">local_activity</i>
                        {{ form_widget(formulaire.codeApe, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.codeApe) }}
                        {{ form_help(formulaire.codeApe) }}
                        {{ form_errors(formulaire.codeApe) }}
                    </div>
                    <div class="input-field col s6">
                        <i class="material-icons prefix">policy</i>
                        {{ form_widget(formulaire.siretSiren, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.siretSiren) }}
                        {{ form_help(formulaire.siretSiren) }}
                        {{ form_errors(formulaire.siretSiren) }}
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m12 l4">
                        <i class="material-icons prefix">streetview</i>
                        {{ form_widget(formulaire.rueEntreprise, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.rueEntreprise) }}
                        {{ form_help(formulaire.rueEntreprise) }}
                        {{ form_errors(formulaire.rueEntreprise) }}
                    </div>
                    <div class="input-field col s12 m6 l4">
                        <i class="material-icons prefix">location_city</i>
                        {{ form_widget(formulaire.villeEntreprise, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.villeEntreprise) }}
                        {{ form_help(formulaire.villeEntreprise) }}
                        {{ form_errors(formulaire.villeEntreprise) }}
                    </div>
                    <div class="input-field col s12 m6 l4">
                        <i class="material-icons prefix">place</i>
                        {{ form_widget(formulaire.codePostalEntreprise, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.codePostalEntreprise) }}
                        {{ form_help(formulaire.codePostalEntreprise) }}
                        {{ form_errors(formulaire.codePostalEntreprise) }}
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        <i class="material-icons prefix">local_phone</i>
                        {{ form_widget(formulaire.telephoneFixeEntreprise, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.telephoneFixeEntreprise) }}
                        {{ form_help(formulaire.telephoneFixeEntreprise) }}
                        {{ form_errors(formulaire.telephoneFixeEntreprise) }}
                    </div>
                    <div class="input-field col s6">
                        <i class="material-icons prefix">smartphone</i>
                        {{ form_widget(formulaire.telephonePortableEntreprise, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.telephonePortableEntreprise) }}
                        {{ form_help(formulaire.telephonePortableEntreprise) }}
                        {{ form_errors(formulaire.telephonePortableEntreprise) }}
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">email</i>
                        {{ form_widget(formulaire.emailEntreprise, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.emailEntreprise) }}
                        {{ form_help(formulaire.emailEntreprise) }}
                        {{ form_errors(formulaire.emailEntreprise) }}
                    </div>
                </div>
                <div class="row">
                    {{ form_widget(formulaire.submit, { 'label': 'Ajouter la fiche de prospection' }) }}
                </div>
                {{ form_end(formulaire) }}
            {% endif %}
        </div>
        <div class="row mt-4 mb-4">
            <a href="{{ path('app_index_index') }}" class="btn monpro waves-effect waves-light center">Retour à l'administration</a>
        </div>
    </div>
{% endblock %}

templates/ficheprospection/edit_fiche_prospection_user.html.twig
{% extends 'base.html.twig' %}

{% block title %} Modifier une fiche de prospection - {{ parent() }} {% endblock %}

{% block body %}
    <div class="container mb-4">
        <div class="row">
            <h1 class="center-align">Modification de la fiche de prospection : {% if fiche is defined %} {{ fiche.nomEntreprise }} {% endif %}</h1>
        </div>
        <div class="row mt-4">
            {% if formulaire is defined %}
                {{ form_start(formulaire, { 'attr': { 'class': 'validate' } }) }}
                <div class="row">
                    <div class="input-field col s6">
                        <i class="material-icons prefix">business</i>
                        {{ form_widget(formulaire.nomEntreprise, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.nomEntreprise) }}
                        {{ form_help(formulaire.nomEntreprise) }}
                        {{ form_errors(formulaire.nomEntreprise) }}
                    </div>
                    <div class="input-field col s6">
                        <i class="material-icons prefix">poll</i>
                        {{ form_widget(formulaire.raisonSocialeEntreprise, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.raisonSocialeEntreprise) }}
                        {{ form_help(formulaire.raisonSocialeEntreprise) }}
                        {{ form_errors(formulaire.raisonSocialeEntreprise) }}
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        <i class="material-icons prefix">local_activity</i>
                        {{ form_widget(formulaire.codeApe, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.codeApe) }}
                        {{ form_help(formulaire.codeApe) }}
                        {{ form_errors(formulaire.codeApe) }}
                    </div>
                    <div class="input-field col s6">
                        <i class="material-icons prefix">policy</i>
                        {{ form_widget(formulaire.siretSiren, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.siretSiren) }}
                        {{ form_help(formulaire.siretSiren) }}
                        {{ form_errors(formulaire.siretSiren) }}
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m12 l4">
                        <i class="material-icons prefix">streetview</i>
                        {{ form_widget(formulaire.rueEntreprise, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.rueEntreprise) }}
                        {{ form_help(formulaire.rueEntreprise) }}
                        {{ form_errors(formulaire.rueEntreprise) }}
                    </div>
                    <div class="input-field col s12 m6 l4">
                        <i class="material-icons prefix">location_city</i>
                        {{ form_widget(formulaire.villeEntreprise, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.villeEntreprise) }}
                        {{ form_help(formulaire.villeEntreprise) }}
                        {{ form_errors(formulaire.villeEntreprise) }}
                    </div>
                    <div class="input-field col s12 m6 l4">
                        <i class="material-icons prefix">place</i>
                        {{ form_widget(formulaire.codePostalEntreprise, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.codePostalEntreprise) }}
                        {{ form_help(formulaire.codePostalEntreprise) }}
                        {{ form_errors(formulaire.codePostalEntreprise) }}
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        <i class="material-icons prefix">local_phone</i>
                        {{ form_widget(formulaire.telephoneFixeEntreprise, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.telephoneFixeEntreprise) }}
                        {{ form_help(formulaire.telephoneFixeEntreprise) }}
                        {{ form_errors(formulaire.telephoneFixeEntreprise) }}
                    </div>
                    <div class="input-field col s6">
                        <i class="material-icons prefix">smartphone</i>
                        {{ form_widget(formulaire.telephonePortableEntreprise, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.telephonePortableEntreprise) }}
                        {{ form_help(formulaire.telephonePortableEntreprise) }}
                        {{ form_errors(formulaire.telephonePortableEntreprise) }}
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">email</i>
                        {{ form_widget(formulaire.emailEntreprise, { 'attr': { 'class': 'validate' } }) }}
                        {{ form_label(formulaire.emailEntreprise) }}
                        {{ form_help(formulaire.emailEntreprise) }}
                        {{ form_errors(formulaire.emailEntreprise) }}
                    </div>
                </div>
                <div class="row">
                    {{ form_widget(formulaire.submit, { 'label': 'Modifier la fiche de prospection' }) }}
                    <a href="{{ path('app_user_liste_fiche_prospection') }}" class="btn monpro waves-effect waves-light center">Annuler</a>
                </div>
                {{ form_end(formulaire) }}
            {% endif %}
        </div>
        <div class="row mt-4 mb-4">
            <a href="{{ path('app_index_index') }}" class="btn monpro waves-effect waves-light center">Retour à l'administration</a>
        </div>
    </div>
{% endblock %}

templates/ficheprospection/liste_fiches_prospection_user.html.twig
{% extends 'base.html.twig' %}

{% block title %} Liste Fiches Prospection - {{ parent() }} {% endblock %}

{% block body %}
    <div class="container mb-4">
        <div class="row">
            <div class="col s12">
                <h1 class="center-align"> Liste de vos fiches de prospection</h1>
            </div>
        </div>
        <div class="row mt-3">
            {% if fiches is defined %}
                <table class="highlight centered responsive-table">
                    <thead>
                    <tr>
                        <th>Nom de l'entreprise</th>
                        <th>Adresse de l'entreprise</th>
                        <th>Email de l'entreprise</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for fiche in fiches %}
                        <tr>
                            <td>{{ fiche.nomEntreprise }}</td>
                            <td>{{ fiche.rueEntreprise }} {{ fiche.codePostalEntreprise }} {{ fiche.villeEntreprise }}</td>
                            <td>{{ fiche.emailEntreprise }}</td>
                            <td>
                                <a href="{{ path('app_user_modifier_fiche_prospection', {id: fiche.id}) }}" class="btn-floating monpro"><i class="material-icons large" title="Modifier">edit</i></a>
                                <a href="#" class="btn-floating monpro"><i class="material-icons large" title="Démarchage Email">email</i></a>
                                <a href="#" class="btn-floating monpro"><i class="material-icons large" title="Démarchage Téléphonique">add_ic_call</i></a>
                                <a href="#" class="btn-floating monpro"><i class="material-icons large" title="Démarchage Courrier Postal">markunread_mailbox</i></a>
                                <a href="#" class="btn-floating monpro"><i class="material-icons large" title="Démarchage Physique">record_voice_over</i></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
        <div class="row mt-4 mb-4">
            <a href="{{ path('app_index_index') }}" class="btn monpro waves-effect waves-light center">Retour à l'administration</a>
        </div>
    </div>
{% endblock %}