src/Entity/Avis.php
<?php

namespace App\Entity;

use App\Repository\AvisRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AvisRepository::class)
 */
class Avis
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $nom_destinataire;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $prenom_destinataire;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $email_destinataire;

    /**
     * @ORM\ManyToOne(targetEntity=Entreprise::class, inversedBy="avis")
     * @ORM\JoinColumn(nullable=false)
     */
    private $entreprise_concernee;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_envoi_enquete;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_reponse_enquete;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $statut_avis;

    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $ip_destinataire;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token_security;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $note_prestation_realisee;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $note_professionnalisme_entreprise;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $note_satisfaction_globale;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $recommander_commentaire_a_entreprise;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $temoignage_video;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $telephone_destinataire;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nb_relance;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_derniere_relance;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomDestinataire(): ?string
    {
        return $this->nom_destinataire;
    }

    public function setNomDestinataire(string $nom_destinataire): self
    {
        $this->nom_destinataire = $nom_destinataire;

        return $this;
    }

    public function getPrenomDestinataire(): ?string
    {
        return $this->prenom_destinataire;
    }

    public function setPrenomDestinataire(string $prenom_destinataire): self
    {
        $this->prenom_destinataire = $prenom_destinataire;

        return $this;
    }

    public function getEmailDestinataire(): ?string
    {
        return $this->email_destinataire;
    }

    public function setEmailDestinataire(string $email_destinataire): self
    {
        $this->email_destinataire = $email_destinataire;

        return $this;
    }

    public function getEntrepriseConcernee(): ?Entreprise
    {
        return $this->entreprise_concernee;
    }

    public function setEntrepriseConcernee(?Entreprise $entreprise_concernee): self
    {
        $this->entreprise_concernee = $entreprise_concernee;

        return $this;
    }

    public function getDateEnvoiEnquete(): ?\DateTimeInterface
    {
        return $this->date_envoi_enquete;
    }

    public function setDateEnvoiEnquete(?\DateTimeInterface $date_envoi_enquete): self
    {
        $this->date_envoi_enquete = $date_envoi_enquete;

        return $this;
    }

    public function getDateReponseEnquete(): ?\DateTimeInterface
    {
        return $this->date_reponse_enquete;
    }

    public function setDateReponseEnquete(?\DateTimeInterface $date_reponse_enquete): self
    {
        $this->date_reponse_enquete = $date_reponse_enquete;

        return $this;
    }

    public function getStatutAvis(): ?string
    {
        return $this->statut_avis;
    }

    public function setStatutAvis(?string $statut_avis): self
    {
        $this->statut_avis = $statut_avis;

        return $this;
    }

    public function getIpDestinataire(): ?string
    {
        return $this->ip_destinataire;
    }

    public function setIpDestinataire(?string $ip_destinataire): self
    {
        $this->ip_destinataire = $ip_destinataire;

        return $this;
    }

    public function getTokenSecurity(): ?string
    {
        return $this->token_security;
    }

    public function setTokenSecurity(?string $token_security): self
    {
        $this->token_security = $token_security;

        return $this;
    }

    public function getNotePrestationRealisee(): ?int
    {
        return $this->note_prestation_realisee;
    }

    public function setNotePrestationRealisee(?int $note_prestation_realisee): self
    {
        $this->note_prestation_realisee = $note_prestation_realisee;

        return $this;
    }

    public function getNoteProfessionnalismeEntreprise(): ?int
    {
        return $this->note_professionnalisme_entreprise;
    }

    public function setNoteProfessionnalismeEntreprise(?int $note_professionnalisme_entreprise): self
    {
        $this->note_professionnalisme_entreprise = $note_professionnalisme_entreprise;

        return $this;
    }

    public function getNoteSatisfactionGlobale(): ?int
    {
        return $this->note_satisfaction_globale;
    }

    public function setNoteSatisfactionGlobale(?int $note_satisfaction_globale): self
    {
        $this->note_satisfaction_globale = $note_satisfaction_globale;

        return $this;
    }

    public function getRecommanderCommentaireAEntreprise(): ?string
    {
        return $this->recommander_commentaire_a_entreprise;
    }

    public function setRecommanderCommentaireAEntreprise(?string $recommander_commentaire_a_entreprise): self
    {
        $this->recommander_commentaire_a_entreprise = $recommander_commentaire_a_entreprise;

        return $this;
    }

    public function getTemoignageVideo(): ?string
    {
        return $this->temoignage_video;
    }

    public function setTemoignageVideo(?string $temoignage_video): self
    {
        $this->temoignage_video = $temoignage_video;

        return $this;
    }

    public function getTelephoneDestinataire(): ?string
    {
        return $this->telephone_destinataire;
    }

    public function setTelephoneDestinataire(?string $telephone_destinataire): self
    {
        $this->telephone_destinataire = $telephone_destinataire;

        return $this;
    }

    public function getNbRelance(): ?int
    {
        return $this->nb_relance;
    }

    public function setNbRelance(?int $nb_relance): self
    {
        $this->nb_relance = $nb_relance;

        return $this;
    }

    public function getDateDerniereRelance(): ?\DateTimeInterface
    {
        return $this->date_derniere_relance;
    }

    public function setDateDerniereRelance(?\DateTimeInterface $date_derniere_relance): self
    {
        $this->date_derniere_relance = $date_derniere_relance;

        return $this;
    }
}

src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Repository\EntrepriseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EntrepriseRepository::class)
 */
class Entreprise
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $raison_sociale;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse_rue;

    /**
     * @ORM\Column(type="string", length=120, nullable=true)
     */
    private $adresse_ville;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $adresse_code_postal;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $telephone_fixe;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $telephone_portable;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $email_contact;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    private $horaires;

    /**
     * @ORM\OneToMany(targetEntity=Avis::class, mappedBy="entreprise_concernee")
     */
    private $avis;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    private $ape;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $siren_siret;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $logo;

    public function slugify($text)
    {
        // replace non letter or digits by -
        $text = preg_replace('#[^\\pL\d]+#u', '-', $text);

        // trim
        $text = trim($text, '-');

        // transliterate
        if (function_exists('iconv'))
        {
            $text = iconv('utf-8', 'us-ascii//TRANSLIT', $text);
        }

        // lowercase
        $text = strtolower($text);

        // remove unwanted characters
        $text = preg_replace('#[^-\w]+#', '', $text);

        if (empty($text))
        {
            return 'n-a';
        }

        return $text;
    }

    public function __construct()
    {
        $this->avis = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        $this->setSlug($this->nom);

        return $this;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->raison_sociale;
    }

    public function setRaisonSociale(?string $raison_sociale): self
    {
        $this->raison_sociale = $raison_sociale;

        return $this;
    }

    public function getAdresseRue(): ?string
    {
        return $this->adresse_rue;
    }

    public function setAdresseRue(?string $adresse_rue): self
    {
        $this->adresse_rue = $adresse_rue;

        return $this;
    }

    public function getAdresseVille(): ?string
    {
        return $this->adresse_ville;
    }

    public function setAdresseVille(?string $adresse_ville): self
    {
        $this->adresse_ville = $adresse_ville;

        return $this;
    }

    public function getAdresseCodePostal(): ?string
    {
        return $this->adresse_code_postal;
    }

    public function setAdresseCodePostal(?string $adresse_code_postal): self
    {
        $this->adresse_code_postal = $adresse_code_postal;

        return $this;
    }

    public function getTelephoneFixe(): ?string
    {
        return $this->telephone_fixe;
    }

    public function setTelephoneFixe(?string $telephone_fixe): self
    {
        $this->telephone_fixe = $telephone_fixe;

        return $this;
    }

    public function getTelephonePortable(): ?string
    {
        return $this->telephone_portable;
    }

    public function setTelephonePortable(?string $telephone_portable): self
    {
        $this->telephone_portable = $telephone_portable;

        return $this;
    }

    public function getEmailContact(): ?string
    {
        return $this->email_contact;
    }

    public function setEmailContact(?string $email_contact): self
    {
        $this->email_contact = $email_contact;

        return $this;
    }

    public function getHoraires(): ?string
    {
        return $this->horaires;
    }

    public function setHoraires(?string $horaires): self
    {
        $this->horaires = $horaires;

        return $this;
    }

    /**
     * @return Collection|Avis[]
     */
    public function getAvis(): Collection
    {
        return $this->avis;
    }

    public function addAvi(Avis $avi): self
    {
        if (!$this->avis->contains($avi)) {
            $this->avis[] = $avi;
            $avi->setEntrepriseConcernee($this);
        }

        return $this;
    }

    public function removeAvi(Avis $avi): self
    {
        if ($this->avis->contains($avi)) {
            $this->avis->removeElement($avi);
            // set the owning side to null (unless already changed)
            if ($avi->getEntrepriseConcernee() === $this) {
                $avi->setEntrepriseConcernee(null);
            }
        }

        return $this;
    }

    public function getApe(): ?string
    {
        return $this->ape;
    }

    public function setApe(?string $ape): self
    {
        $this->ape = $ape;

        return $this;
    }

    public function getSirenSiret(): ?string
    {
        return $this->siren_siret;
    }

    public function setSirenSiret(?string $siren_siret): self
    {
        $this->siren_siret = $siren_siret;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $this->slugify($slug);

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

}

src/Form/EntrepriseType.php
<?php


namespace App\Form;

use App\Entity\Entreprise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Validator\Constraints\File;

class EntrepriseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom',TextType::class, ['required'=>true,'label'=>'Nom de l\'entreprise'])
            ->add('raisonSociale',ChoiceType::class, ['required'=>true,'label'=>'Raison Sociale',
                'choices'=>[
                    "Société à Responsabilité Limitée (SARL)"=>"SARL",
                    "Société par Actions Simplifiées Unipersonnelle (SASU)"=>"SASU",
                    "Société par Actions Simplifiée (SAS)"=>"SAS",
                    "Société Anonyme (SA)"=>"SA",
                    "Entreprise Individuelle (EI)"=>"EI",
                    "Entreprise Unipersonnelle A Responsabilité Limitée (EURL)"=>"EURL",
                    "Entreprise Individuelle A Responsabilité Limitée (EIRL)"=>"EIRL",
                    "Auto-Entreprise (AE)"=>"AE"
                    ]])
            ->add('ape',TextType::class, ['label'=>'Code APE','required'=>true])
            ->add('sirenSiret',TextType::class, ['label'=>'SIREN/SIRET','required'=>true])
            ->add('adresseRue',TextType::class, ['label'=>'Rue','required'=>true])
            ->add('adresseVille',TextType::class, ['label'=>'Ville','required'=>true])
            ->add('adresseCodePostal',TextType::class, ['label'=>'Code Postal','required'=>true])
            ->add('telephoneFixe',TelType::class, ['label'=>'Téléphone Fixe','help'=>'Le format du téléphone fixe est la suivante : 03 XX XX XX XX ou 03.XX.XX.XX.XX','required'=>true])
            ->add('telephonePortable',TelType::class, ['label'=>'Téléphone Portable','help'=>'Le format du téléphone portable est la suivante : 06 XX XX XX XX ou 06.XX.XX.XX.XX','required'=>true])
            ->add('emailContact',EmailType::class, ['label'=>'Email de l\'entreprise','required'=>true])
            ->add('horaires', TextareaType::class, ['label'=>'Horaires de l\'entreprise','required'=>false])
            ->add('logo',FileType::class, ['label'=>'Logo de l\'entreprise','mapped'=>false,'required'=>false,'constraints'=>[new File([
                'maxSize'=>'10240k',
                'mimeTypes'=>['image/jpeg','image/png','image/gif','image/jpg'],
                'mimeTypesMessage'=>'Veuillez télécharger une image avec une extension valide'
            ])]])
            ->add('submit', SubmitType::class, ['attr'=>['class'=>'btn monpro btn-lg btn-primary waves-effect waves-light'],])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Entreprise::class,
        ]);
    }
}

templates/entreprise/view_entreprise.html.twig
{% extends 'base_entreprise.html.twig' %}

{% set currentPath = path(app.request.attributes.get('_route'),
    app.request.attributes.get('_route_params')) %}

{% block title %} Avis Client de {{ entreprise.nom }} {% endblock %}

{% block body %}
    <div class="container mb-4">
        <div class="row">
            <h1 class="center-align">Avis clients de l'entreprise {{ entreprise.nom }}</h1>
        </div>

        <div class="row custom-flex">
            <div class="col s12 m6 l6">
                <img class="responsive-img center-block z-depth-2" src="{{ asset('img/membre-certifie-2020.jpg') }}"  alt="Entreprise Membre du réseau local MonProCertifie"/>
            </div>
            <div class="col s12 m6 l6">
                <div class="card large logo-entreprise">
                    <div class="card-image">
                        <img class="responsive-img center-block" src="{% if entreprise.logo is not empty %}{{ asset('uploads/entreprises/logo/') ~ entreprise.logo }}{% else %} {{ asset('img/gris.png')}} {% endif %}" alt="Logo de l'entreprise {{ entreprise.nom }}">
                        <a href="#infos_procedure" class="btn-floating halfway-fab waves-effect waves-light monpro btn-large pulse modal-trigger"><i class="material-icons">info</i></a>
                    </div>
                    <div class="card-content">
                        <span class="card-title h4">Notation des clients</span>
                        <h5>
                            <strong>
                                {% if avis is defined and avis is not null and avis is not empty %}
                                    {% set moyenne_globale = 0 %}
                                    {% for avi in avis %}
                                        {% set moyenne_globale = moyenne_globale + ((avi.notePrestationRealisee + avi.noteProfessionnalismeEntreprise + avi.noteSatisfactionGlobale) / 3) %}
                                    {% endfor %}
                                    {% set moyenne_globale = moyenne_globale / avis|length %}
                                   {{ moyenne_globale|number_format(2, '.', ',') }} / 5 ({{ avis|length }} avis {% if avis|length > 1 %} controlés) {% else %} controlé) {% endif %}
                                {% else %}
                                    Cette société ne possède pas encore d'avis enregistrés dans nos archives
                                {% endif %}
                            </strong>
                        </h5>
                        <script type="application/ld+json">
                            {
                                "@context": "https://schema.org",
                                "@id": "{{ currentPath }}",
                                "@type": "LocalBusiness",
                                "additionnalType": "Entreprise de construction ou rénovation",
                                "name": "{{ entreprise.nom }}",
                                "legalname": "{{ entreprise.nom }} {{ entreprise.raisonSociale }}",
                                "description": "",
                                "email": "{{ entreprise.emailContact }}",
                                "telephone": "{{ entreprise.telephoneFixe }}",
                                "url": "{{ currentPath }}",
                                "image": "{{ asset('uploads/entreprises/logo/') ~ entreprise.logo }}",
                                "logo": "{{ asset('uploads/entreprises/logo/') ~ entreprise.logo }}",
                                "address": {
                                    "@type": "PostalAddress",
                                    "addressLocality": "{{ entreprise.adresseVille }}",
                                    "addressCountry": "France",
                                    "postalCode": "{{ entreprise.adresseCodePostal }}",
                                    "streetAddress": "{{ entreprise.adresseRue }}"
                                },
                                "areaServed": "France, FR",
                                "priceRange": "EUR",
                                "aggregateRating": {
                                    "@type": "AggregateRating",
                                    "ratingValue": "{{ moyenne_globale|number_format(2, '.', ',') }}",
                                    "ratingCount": "{{ avis|length }}",
                                    "bestRating": "5",
                                    "worstRating": "0"
                                }
                            }
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row lightbackground">
        <div class="container mb-4">
            <div class="row">
                <div class="col s12 m12 l12 mt-4 mb-2">
                    <h3 class="center-align">Liste des avis clients</h3>
                </div>
                {% if avis is defined and avis is not null and avis is not empty %}
                    {% for avi in avis %}
                        <div class="col s12 m6 l6 center-block z-depth-1">
                            {% set moyenne_avis = (avi.noteSatisfactionGlobale + avi.noteProfessionnalismeEntreprise + avi.notePrestationRealisee) / 3 %}
                            <p class="rating center-block">{{ moyenne_avis|number_format(2, '.', ',') }}</p>
                            <p class="value_avis center-align"><strong> {{ moyenne_avis|number_format(2, '.', ',') }} / 5 </strong></p>
                            <p class="value_entreprise center-align">Entreprise concernée : <strong>{{ avi.entrepriseConcernee.nom }}</strong></p>
                            <p class="value_entreprise center-align">Prestations : <strong>{#{% if avi.prestations is not defined and avi.prestations is not empty  %} {{ avi.prestations }} {% else %}#} Non renseigné {#{% endif %}#}</strong></p>
                            <p class="value_commentaire center-align">Commentaire : <strong>{{ avi.recommanderCommentaireAEntreprise }}</strong></p>
                            <p class="value_personne center-align"><strong>{{ avi.prenomDestinataire }} {{ avi.nomDestinataire }}</strong></p>
                        </div>
                    <script type="application/ld+json">
                        {
                            "@context": "https://schema.org",
                            "@type": "Review",
                            "itemReviewed": {
                                "@type": "LocalBusiness",
                                "name": "{{ entreprise.nom }}",
                                "telephone": "{{ entreprise.telephoneFixe }}",
                                "image": "{{ asset('uploads/entreprises/logo/') ~ entreprise.logo }}",
                                "address": {
                                    "@type": "PostalAddress",
                                    "addressLocality": "{{ entreprise.adresseVille }}",
                                    "addressCountry": "France",
                                    "postalCode": "{{ entreprise.adresseCodePostal }}",
                                    "streetAddress": "{{ entreprise.adresseRue }}"
                                },
                                "priceRange": "EUR"
                            },
                            "reviewRating": {
                                    "@type": "Rating",
                                    "ratingValue": "{{ moyenne_avis|number_format(2, '.', ',') }}"
                                },
                            "author": {
                                    "@type": "Person",
                                    "name": "{{ avi.prenomDestinataire }} {{ avi.nomDestinataire }}"
                                },
                            "reviewBody": "{{ avi.recommanderCommentaireAEntreprise }}"
                        }
                    </script>
                    {% endfor %}
                {% else %}
                    <div class="col s12 m12 l12 mb-4">
                        <h6 class="center-align"><strong>Aucun avis enregistré pour le moment</strong></h6>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <div id="infos_procedure" class="modal">
        <div class="modal-content">
            <h4 class="center-align">Informations sur notre procédure de notation</h4>
            <p class="center-align">Le processus de notation et avis écrit est régi par un <strong>processus validé</strong>.
                Un document <strong>authentique contrôlé</strong> est remis au client pour déposer avis et notation
                puis conservé dans nos archives.</p>
        </div>
        <div class="modal-footer">
            <a class="modal-close waves-effect btn-flat monpro waves-effect waves-light white-text">J'ai compris</a>
        </div>
    </div>
{% endblock %}