src/Entity/Avis.php
<?php

namespace App\Entity;

use App\Repository\AvisRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AvisRepository::class)
 */
class Avis
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $nom_destinataire;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $prenom_destinataire;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $email_destinataire;

    /**
     * @ORM\ManyToOne(targetEntity=Entreprise::class, inversedBy="avis")
     * @ORM\JoinColumn(nullable=false)
     */
    private $entreprise_concernee;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_envoi_enquete;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_reponse_enquete;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $statut_avis;

    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $ip_destinataire;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token_security;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $note_prestation_realisee;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $note_professionnalisme_entreprise;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $note_satisfaction_globale;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $recommander_commentaire_a_entreprise;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $temoignage_video;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $telephone_destinataire;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nb_relance;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_derniere_relance;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomDestinataire(): ?string
    {
        return $this->nom_destinataire;
    }

    public function setNomDestinataire(string $nom_destinataire): self
    {
        $this->nom_destinataire = $nom_destinataire;

        return $this;
    }

    public function getPrenomDestinataire(): ?string
    {
        return $this->prenom_destinataire;
    }

    public function setPrenomDestinataire(string $prenom_destinataire): self
    {
        $this->prenom_destinataire = $prenom_destinataire;

        return $this;
    }

    public function getEmailDestinataire(): ?string
    {
        return $this->email_destinataire;
    }

    public function setEmailDestinataire(string $email_destinataire): self
    {
        $this->email_destinataire = $email_destinataire;

        return $this;
    }

    public function getEntrepriseConcernee(): ?Entreprise
    {
        return $this->entreprise_concernee;
    }

    public function setEntrepriseConcernee(?Entreprise $entreprise_concernee): self
    {
        $this->entreprise_concernee = $entreprise_concernee;

        return $this;
    }

    public function getDateEnvoiEnquete(): ?\DateTimeInterface
    {
        return $this->date_envoi_enquete;
    }

    public function setDateEnvoiEnquete(?\DateTimeInterface $date_envoi_enquete): self
    {
        $this->date_envoi_enquete = $date_envoi_enquete;

        return $this;
    }

    public function getDateReponseEnquete(): ?\DateTimeInterface
    {
        return $this->date_reponse_enquete;
    }

    public function setDateReponseEnquete(?\DateTimeInterface $date_reponse_enquete): self
    {
        $this->date_reponse_enquete = $date_reponse_enquete;

        return $this;
    }

    public function getStatutAvis(): ?string
    {
        return $this->statut_avis;
    }

    public function setStatutAvis(?string $statut_avis): self
    {
        $this->statut_avis = $statut_avis;

        return $this;
    }

    public function getIpDestinataire(): ?string
    {
        return $this->ip_destinataire;
    }

    public function setIpDestinataire(?string $ip_destinataire): self
    {
        $this->ip_destinataire = $ip_destinataire;

        return $this;
    }

    public function getTokenSecurity(): ?string
    {
        return $this->token_security;
    }

    public function setTokenSecurity(?string $token_security): self
    {
        $this->token_security = $token_security;

        return $this;
    }

    public function getNotePrestationRealisee(): ?int
    {
        return $this->note_prestation_realisee;
    }

    public function setNotePrestationRealisee(?int $note_prestation_realisee): self
    {
        $this->note_prestation_realisee = $note_prestation_realisee;

        return $this;
    }

    public function getNoteProfessionnalismeEntreprise(): ?int
    {
        return $this->note_professionnalisme_entreprise;
    }

    public function setNoteProfessionnalismeEntreprise(?int $note_professionnalisme_entreprise): self
    {
        $this->note_professionnalisme_entreprise = $note_professionnalisme_entreprise;

        return $this;
    }

    public function getNoteSatisfactionGlobale(): ?int
    {
        return $this->note_satisfaction_globale;
    }

    public function setNoteSatisfactionGlobale(?int $note_satisfaction_globale): self
    {
        $this->note_satisfaction_globale = $note_satisfaction_globale;

        return $this;
    }

    public function getRecommanderCommentaireAEntreprise(): ?string
    {
        return $this->recommander_commentaire_a_entreprise;
    }

    public function setRecommanderCommentaireAEntreprise(?string $recommander_commentaire_a_entreprise): self
    {
        $this->recommander_commentaire_a_entreprise = $recommander_commentaire_a_entreprise;

        return $this;
    }

    public function getTemoignageVideo(): ?string
    {
        return $this->temoignage_video;
    }

    public function setTemoignageVideo(?string $temoignage_video): self
    {
        $this->temoignage_video = $temoignage_video;

        return $this;
    }

    public function getTelephoneDestinataire(): ?string
    {
        return $this->telephone_destinataire;
    }

    public function setTelephoneDestinataire(?string $telephone_destinataire): self
    {
        $this->telephone_destinataire = $telephone_destinataire;

        return $this;
    }

    public function getNbRelance(): ?int
    {
        return $this->nb_relance;
    }

    public function setNbRelance(?int $nb_relance): self
    {
        $this->nb_relance = $nb_relance;

        return $this;
    }

    public function getDateDerniereRelance(): ?\DateTimeInterface
    {
        return $this->date_derniere_relance;
    }

    public function setDateDerniereRelance(?\DateTimeInterface $date_derniere_relance): self
    {
        $this->date_derniere_relance = $date_derniere_relance;

        return $this;
    }
}

src/Form/AvisType.php
<?php


namespace App\Form;


use App\Entity\Avis;
use App\Entity\Entreprise;
use App\Repository\EntrepriseRepository;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class AvisType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nomDestinataire', TextType::class, ['required'=>true,'label'=>'Nom du destinataire'])
            ->add('prenomDestinataire', TextType::class, ['required'=>true,'label'=>'Prénom du destinataire'])
            ->add('emailDestinataire', EmailType::class, ['required'=>true,'label'=>'Email du destinataire'])
            ->add('entrepriseConcernee', EntityType::class,
                [
                    'required'=>true,
                    'label'=>'Entreprise concernée',
                    'class'=>Entreprise::class,
                    'choice_label'=> function (Entreprise $entreprise){
                        return $entreprise->getNom().' - '.$entreprise->getRaisonSociale();
                    }
                ])
            ->add('submit', SubmitType::class, [
                'attr' => [
                    'class' => 'btn monpro btn-lg btn-primary waves-effect waves-light'
                ],
                'label' => 'Envoyer enquête'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(['data_class'=>Avis::class]);
    }
}

templates/avis/edit_avis.html.twig
{% extends 'base.html.twig' %}

{% block title %} Edition Avis - {{ parent() }} {% endblock %}

{% block body %}
    <div class="container mb-4">
        <div class="row">
            <div class="col s12">
                <h1 class="center-align"> Edition de l'avis n°{% if avis is defined %}{{ avis.id }} fait par {{ avis.prenomDestinataire }} {{ avis.nomDestinataire }}{% endif %}</h1>
            </div>
        </div>
        <div class="row">
            <div class="row mt-3">
                {% if formulaire is defined %}
                    {{ form_start(formulaire, { 'attr': { 'class': 'col s12' } }) }}
                    <div class="row">
                        <div class="input-field col s12">
                            <p class="center-align">{{ form_label(formulaire.notePrestationRealisee, null, {'label_attr': {'class': 'radio-label'}}) }}</p>
                            <p class="liste_inputs center-align">
                                {% for child in formulaire.notePrestationRealisee %}
                                    {% if child.vars.value == avis.notePrestationRealisee %}
                                        <label>
                                            {{ form_widget(child, {'attr': {'class': 'with-gap'}, 'checked': true }) }}
                                            <span>{{ form_label(child) }}</span>
                                        </label>
                                    {% else %}
                                        <label>
                                            {{ form_widget(child, {'attr': {'class': 'with-gap'}}) }}
                                            <span>{{ form_label(child) }}</span>
                                        </label>
                                    {% endif %}
                                {% endfor %}
                            </p>
                            {{ form_help(formulaire.notePrestationRealisee) }}
                            {{ form_errors(formulaire.notePrestationRealisee) }}
                        </div>
                    </div>
                    <hr/>
                    <div class="row">
                        <div class="input-field col s12">
                            <p class="center-align">{{ form_label(formulaire.noteProfessionnalismeEntreprise, null, {'label_attr': {'class': 'radio-label'}}) }}</p>
                            <p class="liste_inputs center-align">
                                {% for child in formulaire.noteProfessionnalismeEntreprise %}
                                    {% if child.vars.value == avis.noteProfessionnalismeEntreprise %}
                                        <label>
                                            {{ form_widget(child, {'attr': {'class': 'with-gap'}, 'checked': true }) }}
                                            <span>{{ form_label(child) }}</span>
                                        </label>
                                    {% else %}
                                        <label>
                                            {{ form_widget(child, {'attr': {'class': 'with-gap'}}) }}
                                            <span>{{ form_label(child) }}</span>
                                        </label>
                                    {% endif %}
                                {% endfor %}
                            </p>
                            {{ form_help(formulaire.noteProfessionnalismeEntreprise) }}
                            {{ form_errors(formulaire.noteProfessionnalismeEntreprise) }}
                        </div>
                    </div>
                    <hr/>
                    <div class="row">
                        <div class="input-field col s12">
                            <p class="center-align">{{ form_label(formulaire.noteSatisfactionGlobale, null, {'label_attr': {'class': 'radio-label'}}) }}</p>
                            <p class="liste_inputs center-align">
                                {% for child in formulaire.noteSatisfactionGlobale %}
                                    {% if child.vars.value == avis.noteSatisfactionGlobale %}
                                        <label>
                                            {{ form_widget(child, {'attr': {'class': 'with-gap'}, 'checked': true }) }}
                                            <span>{{ form_label(child) }}</span>
                                        </label>
                                    {% else %}
                                        <label>
                                            {{ form_widget(child, {'attr': {'class': 'with-gap'}}) }}
                                            <span>{{ form_label(child) }}</span>
                                        </label>
                                    {% endif %}
                                {% endfor %}
                            </p>
                            {{ form_help(formulaire.noteSatisfactionGlobale) }}
                            {{ form_errors(formulaire.noteSatisfactionGlobale) }}
                        </div>
                    </div>
                    <hr/>
                    <div class="row mt-4">
                        <div class="input-field col s12">
                            <i class="material-icons prefix">feedback</i>
                            {{ form_widget(formulaire.recommanderCommentaireAEntreprise, { 'attr': { 'class': 'validate materialize-textarea'}, 'value': avis.recommanderCommentaireAEntreprise }) }}
                            {{ form_label(formulaire.recommanderCommentaireAEntreprise) }}
                            {{ form_help(formulaire.recommanderCommentaireAEntreprise) }}
                            {{ form_errors(formulaire.recommanderCommentaireAEntreprise) }}
                        </div>
                    </div>
                    <div class="row flex-end">
                        <div class="input-field col s12 m6 l6">
                            <p class="center-align">{{ form_label(formulaire.temoignageVideo, null, {'label_attr': {'class': 'radio-label'}}) }}</p>
                            <p class="liste_inputs center-align">
                                {% for child in formulaire.temoignageVideo %}
                                    {% if child.vars.value == avis.temoignageVideo %}
                                        <label>
                                            {{ form_widget(child, {'attr': {'class': 'with-gap'}, 'checked': true }) }}
                                            <span>{{ form_label(child) }}</span>
                                        </label>
                                    {% else %}
                                        <label>
                                            {{ form_widget(child, {'attr': {'class': 'with-gap'}}) }}
                                            <span>{{ form_label(child) }}</span>
                                        </label>
                                    {% endif %}
                                {% endfor %}
                            </p>
                            {{ form_help(formulaire.temoignageVideo) }}
                            {{ form_errors(formulaire.temoignageVideo) }}
                        </div>
                        <div class="input-field col s12 m6 l6">
                            <i class="material-icons prefix">phone</i>
                            {{ form_widget(formulaire.telephoneDestinataire, { 'attr': { 'class': 'validate materialize-textarea'}, 'value': avis.telephoneDestinataire }) }}
                            {{ form_label(formulaire.telephoneDestinataire) }}
                            {{ form_help(formulaire.telephoneDestinataire) }}
                            {{ form_errors(formulaire.telephoneDestinataire) }}
                        </div>
                    </div>
                    <hr/>
                    <div class="row mt-4 mb-4 center-align">
                        {{ form_widget(formulaire.submit) }}
                        <a href="{{ path('app_liste_avis') }}" class="btn monpro waves-effect waves-light center">Annuler</a>
                    </div>
                    {{ form_end(formulaire) }}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/avis/formulaire_enquete.html.twig
{% extends 'base.html.twig' %}

{% block title %} Formulaire Enquête - {{ parent() }} {% endblock %}

{% block body %}
    <div class="container mb-4">
        <div class="row">
            <div class="col s12">
                <h1 class="center-align"> Enquête de satisfaction</h1>
            </div>
        </div>
        <div class="row center-align">
            <div class="col s12 m6 offset-m3">
                <div class="card monpro darken-1">
                    <div class="card-content white-text">
                        <span class="card-title">Bonjour {% if avis is defined %} {{ avis.getPrenomDestinataire }} {{ avis.getNomDestinataire }} {% endif %}</span>
                        <p>Nous vous remercions de votre présence pour répondre à notre enquête de satisfaction.</p>
                        <p>Pour rappel, vous avez reçu une prestation de la société : <strong> {{ avis.getEntrepriseConcernee.getNom }} </strong></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            {% if formulaire is defined %}
                {{ form_start(formulaire, { 'attr': { 'class': 'col s12' } }) }}
                <div class="row">
                    <div class="input-field col s12">
                        <p class="center-align">{{ form_label(formulaire.notePrestationRealisee, null, {'label_attr': {'class': 'radio-label'}}) }}</p>
                        <p class="liste_inputs center-align">
                        {% for child in formulaire.notePrestationRealisee %}
                            <label>
                                {{ form_widget(child, {'attr': {'class': 'with-gap'}}) }}
                                <span>{{ form_label(child) }}</span>
                            </label>
                        {% endfor %}
                        </p>
                        {{ form_help(formulaire.notePrestationRealisee) }}
                        {{ form_errors(formulaire.notePrestationRealisee) }}
                    </div>
                </div>
                <hr/>
                <div class="row">
                    <div class="input-field col s12">
                        <p class="center-align">{{ form_label(formulaire.noteProfessionnalismeEntreprise, null, {'label_attr': {'class': 'radio-label'}}) }}</p>
                        <p class="liste_inputs center-align">
                            {% for child in formulaire.noteProfessionnalismeEntreprise %}
                                <label>
                                    {{ form_widget(child, {'attr': {'class': 'with-gap'}}) }}
                                    <span>{{ form_label(child) }}</span>
                                </label>
                            {% endfor %}
                        </p>
                        {{ form_help(formulaire.noteProfessionnalismeEntreprise) }}
                        {{ form_errors(formulaire.noteProfessionnalismeEntreprise) }}
                    </div>
                </div>
                <hr/>
                <div class="row">
                    <div class="input-field col s12">
                        <p class="center-align">{{ form_label(formulaire.noteSatisfactionGlobale, null, {'label_attr': {'class': 'radio-label'}}) }}</p>
                        <p class="liste_inputs center-align">
                            {% for child in formulaire.noteSatisfactionGlobale %}
                                <label>
                                    {{ form_widget(child, {'attr': {'class': 'with-gap'}}) }}
                                    <span>{{ form_label(child) }}</span>
                                </label>
                            {% endfor %}
                        </p>
                        {{ form_help(formulaire.noteSatisfactionGlobale) }}
                        {{ form_errors(formulaire.noteSatisfactionGlobale) }}
                    </div>
                </div>
                <hr/>
                <div class="row mt-4">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">feedback</i>
                        {{ form_widget(formulaire.recommanderCommentaireAEntreprise, { 'attr': {'class': 'validate materialize-textarea', 'maxlength':150, 'data-length':150} }) }}
                        {{ form_label(formulaire.recommanderCommentaireAEntreprise) }}
                        {{ form_help(formulaire.recommanderCommentaireAEntreprise) }}
                        {{ form_errors(formulaire.recommanderCommentaireAEntreprise) }}
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m6 l6">
                        <p class="center-align">{{ form_label(formulaire.temoignageVideo, null, {'label_attr': {'class': 'radio-label'}}) }}</p>
                        <p class="liste_inputs center-align">
                            {% for child in formulaire.temoignageVideo %}
                                {% if child.vars.value == "Non" %}
                                    <label>
                                        {{ form_widget(child, {'attr': {'class': 'with-gap'}, 'checked': true }) }}
                                        <span>{{ form_label(child) }}</span>
                                    </label>
                                {% else %}
                                    <label>
                                        {{ form_widget(child, {'attr': {'class': 'with-gap'}}) }}
                                        <span>{{ form_label(child) }}</span>
                                    </label>
                                {% endif %}
                            {% endfor %}
                        </p>
                        {{ form_help(formulaire.temoignageVideo) }}
                        {{ form_errors(formulaire.temoignageVideo) }}
                    </div>
                    <div class="input-field col s12 m6 l6">
                        <i class="material-icons prefix">phone</i>
                        {{ form_widget(formulaire.telephoneDestinataire, { 'attr': { 'class': 'validate materialize-textarea'} }) }}
                        {{ form_label(formulaire.telephoneDestinataire) }}
                        {{ form_help(formulaire.telephoneDestinataire) }}
                        {{ form_errors(formulaire.telephoneDestinataire) }}
                    </div>
                </div>
                <hr/>
                <div class="row mt-4 mb-4 center-align">
                    {{ form_widget(formulaire.submit) }}
                </div>
                {{ form_end(formulaire) }}
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/avis/liste_avis.html.twig
{% extends 'base.html.twig' %}

{% block title %} Liste Avis - {{ parent() }} {% endblock %}

{% block body %}
    <div class="container mb-4">
        <div class="row">
            <div class="col s12">
                <h1 class="center-align"> Liste des avis</h1>
            </div>
        </div>
        <div class="row mt-3">
            {% if avis is defined %}
                <table class="highlight centered responsive-table">
                    <thead>
                    <tr>
                        <th><label><input type="checkbox" id="select_all" name="select_all" class="filled-in" /><span></span></label></th>
                        <th>Personne</th>
                        <th>Email</th>
                        <th>Entreprise</th>
                        <th>Statut</th>
                        <th>Date envoi</th>
                        <th>Date réponse</th>
                        <th>Nb relance</th>
                        <th>Dernière relance</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for avi in avis %}
                        <tr>
                            <td><label><input type="checkbox" value="{{ avi.id }}" name="avis[{{ avi.id }}]" class="filled-in" id="avis_{{ avi.id }}" /><span></span></label></td>
                            <td>{{ avi.nomDestinataire }} {{ avi.prenomDestinataire }}</td>
                            <td>{{ avi.emailDestinataire }}</td>
                            <td>{{ avi.entrepriseConcernee.nom }}</td>
                            <td class="{% if avi.statutAvis == "En attente de réponse" %}waiting{% else %}answered{% endif %}">{{ avi.statutAvis }}</td>
                            <td>{{ avi.dateEnvoiEnquete|date('d/m/Y H:i',timezone='Europe/Paris') }}</td>
                            <td>{% if avi.dateReponseEnquete is not null %}{{ avi.dateReponseEnquete|date('d/m/Y H:i',timezone='Europe/Paris') }}{% else %} Pas de réponse {% endif %}</td>
                            <td>{{ avi.nbRelance }}</td>
                            <td>{% if avi.dateDerniereRelance is not null %}{{ avi.dateDerniereRelance|date('d/m/Y H:i',timezone='Europe/Paris') }}{% endif %}</td>
                            <td>
                                {% if avi.dateReponseEnquete is not null %}
                                <a href="{{ path('app_voir_avis', {id: avi.id}) }}" class="btn-floating monpro tooltipped" data-position="top" data-tooltip="Voir enqu&ecirc;te"><i class="material-icons large">visibility</i></a>
                                {% if "ROLE_ADMIN" in app.user.roles %}
                                    <a href="{{ path('app_edition_avis', {id: avi.id}) }}" class="btn-floating monpro tooltipped" data-position="top" data-tooltip="Modifier enqu&ecirc;te"><i class="material-icons large">create</i></a>
                                {% endif %}
                                {% else %}
                                <a href="{{ path('app_relance_avis', {id: avi.id}) }}" class="btn-floating monpro tooltipped" data-position="top" data-tooltip="Envoyer relance"
                                   onclick="return confirm('Êtes-vous sûr de vouloir envoyer la relance e-mail ?');"
                                ><i class="material-icons large">send</i></a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
        <div class="row center-align mt-4">
            {{ knp_pagination_render(avis,'bundles/Paginator/Pagination/materialize_pagination.html.twig') }}
        </div>
        <div class="row mt-4 mb-4">
            <a data-path="{{ path('app_export_avis') }}" class="btn monpro waves-effect waves-light center" id="btn_export">Exporter les avis sélectionnés</a>
            <a href="{{ path('app_index_admin') }}" class="btn monpro waves-effect waves-light center">Retour à l'administration</a>
        </div>
    </div>
{% endblock %}

templates/avis/view_avis.html.twig
{% extends 'base.html.twig' %}

{% block title %} {% endblock %}

{% set globale_note = (avis.notePrestationRealisee + avis.noteProfessionnalismeEntreprise + avis.noteSatisfactionGlobale) / 3 %}

{% block body %}
    <div class="container mb-4">
        <div class="row">
            <div class="col s12">
                <h1 class="center-align"> Avis {% if avis is defined %} (Id:{{ avis.id}}) de {{ avis.prenomDestinataire }} {{ avis.nomDestinataire }} {% endif %}</h1>
            </div>
        </div>
        <div class="row">
            <div class="col s10 offset-s1">

            </div>
        </div>
        <div class="row">
            <div class="col s12 m10 offset-m1">
                <div class="card monpro darken-1">
                    <div class="card-content white-text">
                        <span class="card-title center-align">Avis de {% if avis is defined %} {{ avis.getPrenomDestinataire }} {{ avis.getNomDestinataire }} {% endif %}</span><br/>
                        <p class="center-align">L'entreprise concernée était : <strong>{{ avis.entrepriseConcernee.nom }}</strong></p>
                        <p class="center-align">La réponse à l'enquête a été enregistrée le : <strong>{{ avis.dateReponseEnquete|date('d/m/Y',timezone='Europe/Paris') }} à {{ avis.dateReponseEnquete|date('H:i',timezone='Europe/Paris') }}</strong></p>
                        <br/>
                        <p class="center-align">La note pour la prestation faite par l'entreprise est de : <strong><span class="{% if avis.notePrestationRealisee < 1.5 %} bas {% elseif avis.notePrestationRealisee > 1.5 and avis.notePrestationRealisee < 3.5 %} moyen {% else %} haut {% endif %}">{{ avis.notePrestationRealisee }} / 5</span></strong></p>
                        <p class="center-align">La note pour le professionnalisme de l'entreprise est de : <strong><span class="{% if avis.noteProfessionnalismeEntreprise < 1.5 %} bas {% elseif avis.noteProfessionnalismeEntreprise > 1.5 and avis.noteProfessionnalismeEntreprise < 3.5 %} moyen {% else %} haut {% endif %}">{{ avis.noteProfessionnalismeEntreprise }} / 5</span></strong></p>
                        <p class="center-align">La note pour la satisfaction globale est de : <strong><span class="{% if avis.noteSatisfactionGlobale < 1.5 %} bas {% elseif avis.noteSatisfactionGlobale > 1.5 and avis.noteSatisfactionGlobale < 3.5 %} moyen {% else %} haut {% endif %}">{{ avis.noteSatisfactionGlobale }} / 5</span></strong></p><br>
                        <p class="center-align"><strong>La moyenne des 3 notes précédentes est de : <span class="{% if globale_note < 1.5 %} bas {% elseif globale_note > 1.5 and globale_note < 3.5 %} moyen {% else %} haut {% endif %}"> {{ globale_note|number_format(2,',','.')  }} / 5 </span></strong></p>
                        <br/>
                        <p>Le commentaire / la recommandation de la personne concernant l'entreprise : <strong><blockquote>{{ avis.recommanderCommentaireAEntreprise }}</blockquote></strong></p>
                        <br/>
                        <p class="center-align">Est-ce que la personne souhaite être contacté pour un témoignage vidéo : <strong>{{ avis.temoignageVideo }}</strong></p>
                        <p class="center-align">Le numéro de téléphone de la personne : <strong>{% if avis.telephoneDestinataire is not null %}{{ avis.telephoneDestinataire }}{% else %}Pas renseigné{% endif %}</strong></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-4 mb-4 center-align">
            <a href="{{ path('app_liste_avis') }}" class="btn monpro waves-effect waves-light center">Retour aux avis</a>
        </div>
    </div>
{% endblock %}